"""
vial_export.py — Generates a Vial-firmware ZIP (in-memory BytesIO).

Per official docs: https://get.vial.today/docs/porting-to-vial.html

ZIP structure:
  {kb}/
  ├── INSTALL.md
  ├── config.h
  ├── info.json
  ├── keyboard.h
  ├── rules.mk
  └── keymaps/
      ├── default/keymap.c
      └── vial/
          ├── keymap.c
          ├── rules.mk
          ├── config.h
          └── vial.json
"""
import io
import json
import random
import zipfile
from .board_profiles import BOARD_PROFILES


def _random_uid():
    return ", ".join(f"0x{random.randint(0,255):02X}" for _ in range(8))


def _build_vial_kle(kle_raw, keys):
    """
    Given the original KLE JSON array and the list of keys,
    returns a new KLE JSON array where the primary label is replaced by "r,c" 
    so the original rotations (r, rx, ry) and positions are perfectly preserved.
    """
    if not kle_raw:
        return []
        
    new_kle = []
    key_idx = 0
    for row in kle_raw:
        if isinstance(row, dict):
            new_kle.append(row.copy())
            continue
            
        new_row = []
        for item in row:
            if isinstance(item, dict):
                new_row.append(item.copy())
            elif isinstance(item, str):
                if key_idx < len(keys):
                    mat = keys[key_idx].get("matrix", [0, 0])
                    new_row.append(f"{mat[0]},{mat[1]}")
                    key_idx += 1
                else:
                    new_row.append("0,0")
            else:
                new_row.append(item)
        new_kle.append(new_row)
    return new_kle


def generate_vial_zip(routing_result):
    """
    routing_result: dict returned by router.route_layout()
    Returns: BytesIO containing the ZIP archive.
    """
    layout      = routing_result["layout"]
    matrix_pins = routing_result["matrix_pins"]
    active_rows = matrix_pins["rows"]
    active_cols = matrix_pins["cols"]
    is_split    = routing_result.get("split", False)
    board_id    = routing_result.get("board_used", "waveshare_2040_plus")
    kb_name_raw = routing_result.get("keyboard_name", "custom_handwired")
    kb_name     = kb_name_raw.lower().replace(" ", "_").replace("-", "_")

    board       = BOARD_PROFILES.get(board_id, {})
    mcu         = board.get("mcu", "RP2040")
    boot        = board.get("bootloader", "rp2040")
    uid         = _random_uid()

    # Logical matrix dimensions
    logical_rows = routing_result.get("logical_rows", len(active_rows))
    num_cols     = len(active_cols)
    layout_name  = "LAYOUT"

    # ── Generate file contents ────────────────────────────────────────────────

    split_block = ""
    if is_split:
        split_block = (
            "\n\n// Split keyboard — REQUIRED: configure your serial/TRRS pin:\n"
            "// #define SERIAL_USART_FULL_DUPLEX\n"
            "// #define SERIAL_USART_TX_PIN GP0   // adjust\n"
            "// #define SERIAL_USART_RX_PIN GP1   // adjust\n"
            "// Or for Pro Micro half-duplex: #define SOFT_SERIAL_PIN D2\n"
            "#define SPLIT_USB_DETECT"
        )

    config_h = f"""\
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by QMK Wiring Visualizer v3
#pragma once

#define MATRIX_ROWS {logical_rows}
#define MATRIX_COLS {num_cols}
#define MATRIX_ROW_PINS {{ {', '.join(active_rows)} }}
#define MATRIX_COL_PINS {{ {', '.join(active_cols)} }}
#define DIODE_DIRECTION COL2ROW{split_block}
"""

    keyboard_h = """\
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#include "quantum.h"
"""

    rules_mk = f"""\
# Auto-generated by QMK Wiring Visualizer v3
# DO NOT add VIA_ENABLE / VIAL_ENABLE here — put in keymaps/vial/rules.mk

MCU = {mcu}
BOOTLOADER = {boot}
{("SPLIT_KEYBOARD = yes" if is_split else "")}
"""

    vial_rules_mk = """\
# Vial keymap rules — both lines required, do not remove VIA_ENABLE
VIA_ENABLE = yes
VIAL_ENABLE = yes
"""

    vial_config_h = f"""\
/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

/* Unique Vial keyboard ID */
#define VIAL_KEYBOARD_UID {{{uid}}}

/* Unlock combo: hold [0,0]+[0,1] for ~3s to unlock security settings */
#define VIAL_UNLOCK_COMBO_ROWS {{ 0, 0 }}
#define VIAL_UNLOCK_COMBO_COLS {{ 0, 1 }}
"""

    kc_args = ", ".join("KC_TRNS" for _ in layout)
    keymap_c = f"""\
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by QMK Wiring Visualizer v3

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {{
    [0] = {layout_name}({kc_args}),
    [1] = {layout_name}({kc_args}),
    [2] = {layout_name}({kc_args}),
    [3] = {layout_name}({kc_args}),
}};
"""

    # info.json
    info = {
        "keyboard_name": kb_name,
        "manufacturer":  routing_result.get("manufacturer", "Custom Handwired"),
        "url": "",
        "maintainer": "handwired",
        "usb": {"vid": "0xFEED", "pid": "0x0000", "device_version": "0.0.1"},
        "processor":   mcu,
        "bootloader":  boot,
        "diode_direction": "COL2ROW",
        "matrix_pins": {"rows": active_rows, "cols": active_cols},
        "layouts": {
            layout_name: {
                "layout": [
                    {k: round(v, 2) if isinstance(v, float) else v
                     for k, v in {
                         "matrix": key.get("matrix"),
                         "x":      key.get("x", 0),
                         "y":      key.get("y", 0),
                         **({"w": key["w"]} if key.get("w", 1) != 1 else {}),
                         **({"h": key["h"]} if key.get("h", 1) != 1 else {}),
                         **({"r": key["r"]} if key.get("r", 0) != 0 else {}),
                         **({"rx": key["rx"]} if key.get("rx", 0) != 0 else {}),
                         **({"ry": key["ry"]} if key.get("ry", 0) != 0 else {}),
                     }.items() if v is not None}
                    for key in layout
                ]
            }
        },
    }
    if is_split:
        info["split"] = {"enabled": True}

    # vial.json
    vial_json = {
        "name":      kb_name,
        "vendorId":  "0xFEED",
        "productId": "0x0000",
        "lighting":  "none",
        "matrix":    {"rows": logical_rows, "cols": num_cols},
        "layouts":   {"keymap": _build_vial_kle(routing_result.get("kle_raw", []), layout)},
    }

    install_md = f"""\
# {kb_name} — Vial Firmware: Compile & Flash Guide
> Auto-generated by QMK Wiring Visualizer v3

## Prerequisites
- Working [QMK build environment](https://docs.qmk.fm/#/newbs_getting_started)
- Git

## Step 1 — Clone vial-qmk (once)
```bash
git clone https://github.com/vial-kb/vial-qmk.git
cd vial-qmk && make git-submodule
```
> ⚠️ Keep vial-qmk **outside** your existing qmk_firmware folder.

## Step 2 — Copy your keyboard
```bash
cp -r {kb_name}/  vial-qmk/keyboards/handwired/
```

## Step 3 — Verify environment
```bash
cd vial-qmk && qmk doctor
```

## Step 4 — Compile
```bash
make handwired/{kb_name}:vial
```
> Use `make`, **not** `qmk compile`.

## Step 5 — Flash
```bash
make handwired/{kb_name}:vial:flash
```

## After Flashing
1. Open [Vial GUI](https://get.vial.today/download/)
2. Go to **Security → Unlock** (hold top-left two keys ~3s)
3. Remap in real time without reflashing
"""

    # ── Assemble ZIP ─────────────────────────────────────────────────────────
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        base = kb_name + "/"
        zf.writestr(base + "INSTALL.md",   install_md)
        zf.writestr(base + "config.h",     config_h)
        zf.writestr(base + "info.json",    json.dumps(info, indent=2))
        zf.writestr(base + "keyboard.h",   keyboard_h)
        zf.writestr(base + "rules.mk",     rules_mk)
        zf.writestr(base + "keymaps/default/keymap.c", keymap_c)
        zf.writestr(base + "keymaps/vial/keymap.c",    keymap_c)
        zf.writestr(base + "keymaps/vial/rules.mk",    vial_rules_mk)
        zf.writestr(base + "keymaps/vial/config.h",    vial_config_h)
        zf.writestr(base + "keymaps/vial/vial.json",   json.dumps(vial_json, indent=2))
    buf.seek(0)
    return buf, kb_name
